### ISSUE TITLE
Vanced Crashing in Pie 9.1 One PLus6T

### ISSUE THREAD

**Issue by nishchalraj** [Magisk-Modules-Repo/iYTBP-Vanced-Magisk-Repo#10]
The time I start changing the video quality from the video given option, it crashes (for the first time only) and then restarting the app has no issue.
**NOTE :** My device is not rooted and I using the non-rooted White/Black version released on 14th of February.

**Comment by zanezam** [comment]
late but still: this is not non-root version so i will close that. meanwhile u have some new versions to try. tip: join us on xda/dicord toget some support from non-root users and devs
