### ISSUE TITLE
README.md Link to "Latest Changelog" leads to 404 error

### ISSUE THREAD

**Issue by bwalsh0** [Magisk-Modules-Repo/iYTBP-Vanced-Magisk-Repo#11]
I don't know if you're still maintaining changelogs, but the past few versions haven't had any changelogs listed in the XDA thread or on the newer website. I also couldn't find any other possible links to one on the website.

URL in question: https://vanced.app/Home/Changelogs

**Comment by zanezam** [comment]
thx yes changelogs link was long broken now fixed in this 190ee343e23609cd77268a2d5b5040cfc83da7d2
bei removing it ;-) new changelog location is wip.
