### ISSUE TITLE
Sound Problem and translation add request

### ISSUE THREAD

**Issue by History-exe** [Magisk-Modules-Repo/iYTBP-Vanced-Magisk-Repo#13]
1. After install the latest version Youtube Vanced black themed(V.2.0.7) on YouTube (V.14.10.53 Build 01.30.30), sometimes there is no sound when video played. Especially when play a list of videos. The first and second videos may have sound, but others are not unless you slide the progress bar to its beginning by hand.

1. One more thing is do you want to add other language translation? Maybe I can help you with the zh_CN one.

**Comment by History-exe** [comment]
And I noticed that sometimes there are no sound problems when other apps play videos.

**Comment by zanezam** [comment]
well i only can suggest that u try stock youtube as well and see if its the same with it (which i strongly gues). beside of never having them myself i actually never heard of any sound issues with any youtube app. but well i might have miss it ;-) can't help u with that sry. 
second: here is the translation site https://vanced.oneskyapp.com/collaboration/project/302988
thx for contribution!
