### ISSUE TITLE
Create all-in-one version with standard version and black one

### ISSUE THREAD

**Issue by MarcAnt01** [Magisk-Modules-Repo/iYTBP-Vanced-Magisk-Repo#15]
User could choose the version he wants to install with volume key. Switching to Unity is necessary, I can embark a pull request if you agree

**Comment by zanezam** [comment]
thx for the suggestion.ehm combining into one zip? hm tbh i won't go for that as the size of the pack already is quite big. if we combine both versions (which i btw already considered when starting with this) ppl always have to download both versions at once so everyone potentially have to download double of size he/she wants/needs. and the second reason for not doing it is switching to unity means to move away too much from magisk template base which i actually don't want to.
