### ISSUE TITLE
Merge ? / Crash ?

### ISSUE THREAD

**Issue by ShadyGaDa** [Magisk-Modules-Repo/iYTBP-Vanced-Magisk-Repo#5]
Maybe merge both versions for simplicity or go an work for google. Much better than theirs. 
Posted logcat in other repo. Gets confusing.

**Comment by zanezam** [comment]
merge? hmm actually maybe meanwhile i can imagine a flag controlled combined version but the package size doubles then which is already a bit of a problem the big size of the package... anyway u activated the wheels again will try a round when i have time ;)
another approach would be to make all the themes switchable in the app itself so we need only one but as of now i only can say that discussions about such a function are ongoing (at least). about the crash i will answer in the other repo but first i have to look so gimme some time... 
and eh working for google? never! but hey actually we all already are working for them, don't we? :)
