### ISSUE TITLE
[Suggestion] Add an option to change the startup tab

### ISSUE THREAD

**Issue by Insane-96** [Magisk-Modules-Repo/iYTBP-Vanced-Magisk-Repo#6]
When you open youtube you're always in the "Home"
Would be cool to be able to change it to "Subscriptions" or (for some reasons) "Trends"

**Comment by zanezam** [comment]
hi and thx this was already requested previously by multiple people on other channels. indeed that would be a handy thing to have. it's on our screen but i dunno any status or if that is even possible to do atm. sry
